#!/bin/sh
branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

GREEN='\033[0;32m'
RED='\033[0;31m'
NORMAL='\033[0m'

if [[ "$branch" =~ ^(master$|^develop$|^main$|feature\/[a-zA-Z0-9\.-]|bugfix\/[a-zA-Z0-9\.-]|experiment\/[a-zA-Z0-9\.-]|release\/[0-9\.-]|hotfix\/[0-9\.-]) ]]
then
    echo "Valid git branch name: $GREEN$branch$NORMAL"
else
    echo "Invalid git branch name: $RED$branch$NORMAL"
    exit 1
fi